### ISSUE TITLE
Message Distribution is not uniform (at all) with weights less than 4

### ISSUE THREAD

**Issue by cogitaria-admin** [rabbitmq/rabbitmq-consistent-hash-exchange#44] opened 2019-07-19 01:04 UTC
I'm using RabbitMQ **3.6.9** including the rabbitmq_consistent_hash_exchange **3.6.9**.

Running the python example as-is does not produce anything close to a uniform message distribution between q1 and q2 (each with weight 1) or q3 and q4 (each with weight 2). 

There is no discussion on why you would want to have some queues weighted higher than others. I'm assuming you would bind more _powerful_ consumers to the higher weighted queues?  A word or two on that would help.

In any event, all of my consumers are similar machines, so I changed all weights to the value of **1** with the expectation of a uniform distribution. 

Here are the (non-uniform) results:

`
q1: 16,849
q2: 9,423
q3: 11,531
q4: 62,197
`

Happily, changing the weight to **8** buckets for each queue (instead of 1) produces a very smooth distribution of about 25K messages each!  Using random GUIDs as the routing key (instead of integer) also resulted in a nice uniform distribution. 

I repeated the experiment with 4 buckets (weight) per queue and the distribution started showing signs of being lumpy.  3 was worse. 2 was worse still. 1 is all but unusable.

**Comment by michaelklishin** [comment] 2019-07-19 01:06
Duplicate of #37, which has been addressed in `3.7.8` and further corrected in `3.7.10` or so.

RabbitMQ `3.6.x` has been out of support for [14 months now](https://www.rabbitmq.com/changelog.html). Please [upgrade](https://www.rabbitmq.com/upgrade.html).

**Closed by michaelklishin** 2019-07-19 01:06 UTC
